v1
olavlan/it2 pull request #1
Opened 2023-03-06 14:42 UTC by olavlan

I denne versjonen er den konseptuelle delen ferdig.

2023-03-09 17:38 UTC, astyve approved these changes
Introduksjonen synest jeg er veldig bra. Gir en god oversikt over helheten, og vi ser av strukturen her, hvordan du legger opp den pedagogiske tilnærmingen her, med bla å introdusere objektene før klassene osv.

2023-03-09 19:38 UTC, astyve requested changes
Svært mye bra her nå Olav! Se igjennom kommentarene mine og se om du er enig. Tar gjerne en prat med deg når du har fått oversikt, så kan vi diskutere noen av de prinsipielle kommentarene jeg har lagt inn ;-)

2023-03-09 19:38 UTC, astyve commented on innhold/4_objekter_klasser_mer.md
> +Merk hvor mye enklere `Bok`-klassen har blitt! Vi har ikke mistet noe funksjonalitet knyttet til anmeldelser, men delegert ansvaret til en ny klasse!
Her er du igjen litt tilbake på "det er bra om koden blir enklere"...som i "færre linjer = god kode" (satt litt på spissen). Få heller mer fokus på at "NÅ har klassen Bok kun **ett ansvar/spiller kun en rolle** igjen". Det er bra, og gjør det mye enklere å f.eks. kunne gjenbruke klassen Bok i en annen applikasjon der bøker ikke skal anmeldes.

2023-03-09 19:38 UTC, astyve commented on innhold/4_objekter_klasser_mer.md
> +<img src="objektdiagram_bok_oppdeling2.svg" width="100%">
I prinsippet ville vi ha forsøkt å unngå koblingen fra bok til bokanmeldelse. Skal klassen Bok virkelig kunne stå på egne ben, bør ikke Bok-klassen vite at det finnes en klasse som heter Bokanmeldelse. Det at en bok har en (eller flere) anmeldelser, vil man kunne "regne seg frem til"/utlede ved å gå igjennom _**samlingen av**_ anmeldelser. Denne samlingen av anmeldelser bør være et register hos biblioteket og ikke ligge i hver bok...

Men det er mulig dette blir litt for komplisert på dette nivået...

2023-03-09 19:38 UTC, astyve commented on innhold/4_objekter_klasser_mer.md
> +* Når et objekt benytter en metode som tilbys av et annet objekt, og får svar tilbake, har vi kommunikasjon mellom objekter. Metodene som kan benyttes i objektkommunikasjon kalles offentlige metoder.
Legg gjerne til:

"....,har vi kommunikasjon mellom objekter. _**Vi sier at objektene samhandler**_."

2023-03-09 19:38 UTC, astyve commented on innhold/5_arv.md
> +Vi kan nå opprette en `Film`-klasse, det vil si en oppskrift for alle filmobjekter:
"oppskrift" byttes til "mal"

2023-03-09 19:38 UTC, astyve commented on innhold/5_arv.md
> +Her kan vi benytte oss av *arv*. Måten vi gjør det på er å lage en basisklasse som inneholder de egenskapene og metodene som finnes i begge klassene. Deretter kan vi si at`Bok` og `Film`-klassen skal
"...skal bygge videre på denne basisklassen. Vi sier at Bok og Film _**arver**_ egenskapene og metodene til basisklassen"

2023-03-09 19:38 UTC, astyve commented on innhold/5_arv.md
> +- Vi sier at`Utlånsobjekt` er *superklassen* til `Bok` og `Film`.
Og at Film og Bok er _subklassene_ til Utlånsobjekt-klassen.

2023-03-09 19:38 UTC, astyve commented on innhold/5_arv.md
> +- Vi unngår å repetere de samme metodene i flere klasser. I stedet definerer vi disse ett sted, nemlig i superklassen. Det betyr at vi også unngår duplikasjoner av kode, og det blir lettere å gjøre e
"...unngår duplikasjoner av kode..." -> "...unngår duplisering av kode.."

2023-03-09 19:38 UTC, astyve commented on innhold/5_arv.md
> +- Vi følger prinsippet om ett ansvar per klasse. En klasse som heter "Bok" bør kun ha ansvar for det som har med bøker å gjøre. Å registrere utlån er ikke et ansvar som `Bok`-klassen trenger å ha.
OBS! OBS! Her er vi litt ute og sykler. Husk at klassen Bok ved å arve fra Utlånsobjekt også ER et utlånsobjekt. D.v.s. klassen Bok har fortsatt ansvaret/rollen BÅDE til Bok OG til Utlånsobjekt-klassen. Så her bør vi IKKE dra inn prinsippet om ett ansvar....

2023-03-09 19:38 UTC, astyve commented on innhold/5_arv.md
> +Måten vi leser dette diagrammet på er:
Pass på notasjonen i diagrammet. "null eller flere" skal vises om "0..*", du mangler '*' i diagrammet.

2023-03-09 19:38 UTC, astyve commented on innhold/5_arv.md
> +2. Ansvar for utlån er delegert til superklassen `Utlånsobjekt`. Klassen`Bok` får alle egenskapene og metodene til superklassen.
NB!! Ref kommentar over. Vi har IKKE delegert ansvar for utlån til Utlånsobjekt-klassen. Men vi har _**abstrahert/generalisert**_ en del av ansvaret som klassene Bok og Film har til superklassen Utlånsobjekt.

2023-03-13 12:35 UTC, olavlan commented on innhold/1_introduksjon.md
> +De ulike måtene kalles gjerne *programmeringsparadigmer*. Ulike språk benytter seg av ulike paradigmer, eller en kombinasjon. Java er et typisk objektorientert programmeringsspråk, mens SQL er et dek
Rettet

2023-03-13 12:42 UTC, olavlan commented on innhold/1_introduksjon.md
> +person1 = Person()
Skriver en kommentar om dette nederst. Jeg ville introdusere færrest mulig konsepter i dette kapitlet.

2023-03-13 12:46 UTC, olavlan commented on innhold/1_introduksjon.md
> +
Jeg synes det blir for mye å inkludere en `__init__()`-funksjon med tanke på hva som er hensikten med kapitlet, som er å være en relativt lettlest introduksjon. Kan heller vurdere å droppe kapitlet hvis det går for mye i retning av feillæring.

2023-03-13 12:46 UTC, olavlan commented on innhold/3_klasse.md
> +
Endrer alle forekomster av "oppskrift" med "mal"

2023-03-13 12:51 UTC, olavlan commented on innhold/5_arv.md
> +- Vi unngår å repetere de samme metodene i flere klasser. I stedet definerer vi disse ett sted, nemlig i superklassen. Det betyr at vi også unngår duplikasjoner av kode, og det blir lettere å gjøre e
rettet

2023-03-13 12:52 UTC, olavlan commented on innhold/5_arv.md
> +- Vi følger prinsippet om ett ansvar per klasse. En klasse som heter "Bok" bør kun ha ansvar for det som har med bøker å gjøre. Å registrere utlån er ikke et ansvar som `Bok`-klassen trenger å ha.
Fjernet

2023-03-13 12:53 UTC, olavlan commented on innhold/5_arv.md
> +2. Ansvar for utlån er delegert til superklassen `Utlånsobjekt`. Klassen`Bok` får alle egenskapene og metodene til superklassen.
Fjernet

2023-03-13 12:55 UTC, olavlan commented on innhold/3_klasse.md
> +Det kan være nyttig å tenke over antall parametre handlingene trenger. Generelt ønsker vi færrest mulig parametre. Lange parameterlister kan være et tegn på at en handling bør flyttes til en annen kl
Fjernet siste avsnitt

2023-03-13 12:58 UTC, olavlan commented on innhold/3_klasse.md
> +* Et UML-klassediagram er en standardisert måte å skissere klasser.
Rettet, men jeg venter med å nevne relasjoner mellom klasser til litt senere. Vil ikke introdusere for mange nye konsepter på en gang, men heller litt og litt.

2023-03-13 12:59 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +Først sier vi hvilken klasse objektet kommer fra, deretter skriver vi de viktigste egenskapene i parenteser.
Rettet

2023-03-13 13:00 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +Dette er oppskrifter som vi bruker til å opprette objekter. Tenk deg at vi vil registrere boken *Sofies verden* i systemet. Vi må da opprette et `Bok`-objekt. En vanlig måte å skrive et slikt objekt
Rettet

2023-03-13 13:00 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +Tilsvarende kan vi skrive ned Person-objekter:
Rettet

2023-03-13 13:05 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +<img src="klasser_med_navn.svg" width="30%">
Reformulert slik at det blir færre gjentakelser. Jeg lar likevel diagrammet stå, slik at leseren slipper å klikke seg tilbake til forrige artikkel i publiseringsplattformen (hver seksjon i mine dokumenter blir sider som man klikker seg gjennom i publiseringsplattformen).

2023-03-13 13:33 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +Her definerer vi egenskaper og handlinger i de ulike klassene. Handlinger, altså ting vi kan gjøre med objekter, kalles vanligvis *metoder*. Vi kan si følgende om `Bok`-klassen:
Har vært upresis med begrepene, og har nå endret alle forekomster av "egenskap" med enten "datafelt" eller "verdi", avhengig av kontekst

2023-03-13 13:43 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +- Vi kan bruke klassen til å opprette `Bok`-objekter. Da får hvert objekt en kopi av metodene, og datafeltene fylles med spesifikke verdier.
Endret formulering

2023-03-13 13:45 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +Målet vårt var at egenskapen `lånehistorikk` skal lagre tidligere utlån. Nå vet hvilken datatype vi trenger, nemlig `list[Utlån]`! Vi kan legge til dette i klassediagrammet:
Rettet

2023-03-13 13:58 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +- Det første objektet har overskriften `bok1: Bok`. Dette betyr at vi har gitt objektet navnet `bok1`, og at datatypen er`Bok`. Et objekt trenger ikke å ha et navn, og da skriver vi kun datatypen med
Rettet formulering, og inkludert en "advarsel" som oppsummerer ditt poeng

2023-03-13 14:05 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +Et viktig prinsipp er at **en metode bør kun ha ett ansvar**. Dette må vi tenke på når vi skal legge til ny funksjonalitet i bokprogrammet vårt. Kanskje det skal være mulig å skrive en anmeldelse sam
Endret til riktige begreper alle steder

2023-03-13 14:11 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +Metodene vi har lagt til kalles gjerne *delmetoder*, fordi de utfører delprosesser, og sørger for at`regn_ut_gjennomsnittsvurdering()` kun har ansvar for selve utregningen. Fordelen med denne oppdeli
Har omorganisert slik at lesbarhet er det første punktet

2023-03-13 14:14 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +Hvordan legger vi til en konstruktør i klassen? Vi definerer en metode med samme navn som klassen, og med noen ønskede parametre. En konstruktør for `Bok`-klassen kan fderforvære `Bok(tittel, forfatt
Rettet

2023-03-13 14:14 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +Prinsippet om ett ansvar brukes også på klasser. Vi kan ikke si at en klasse bare skal gjøre én ting, men den bør ha ett *ansvarsområde* . Det betyr at `Bok`-klassen bare skal ha ansvar for egenskape
Skrevet om

2023-03-13 14:21 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +Merk hvor mye enklere `Bok`-klassen har blitt! Vi har ikke mistet noe funksjonalitet knyttet til anmeldelser, men delegert ansvaret til en ny klasse!
Endret, fokuserer nå på ansvar i stedet

2023-03-13 14:24 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +<img src="objektdiagram_bok_oppdeling2.svg" width="100%">
Denne må jeg tenke litt på. Oppretter issue

2023-03-13 14:26 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +* Vi bør følge prinsippet om at en metode bare har ett ansvar. En metode skal altså bare utføre én handling. Dersom flere steg er nødvendig, bør disse delegeres til delmetoder.
Rettet

2023-03-13 14:28 UTC, olavlan commented on innhold/4_objekter_klasser_mer.md
> +* Når et objekt benytter en metode som tilbys av et annet objekt, og får svar tilbake, har vi kommunikasjon mellom objekter. Metodene som kan benyttes i objektkommunikasjon kalles offentlige metoder.
Inkludert

2023-03-13 14:28 UTC, olavlan commented on innhold/5_arv.md
> +Vi kan nå opprette en `Film`-klasse, det vil si en oppskrift for alle filmobjekter:
Rettet

2023-03-13 15:24 UTC, olavlan commented on innhold/3_klasse.md
> +<img src="klasse_bokhylle.svg" width="15%">
Enig i at Bokhylle ikke tilfører noe særlig. Kanskje vi kan inkludere en seksjon med refleksjoner rundt den valgte løsningen? Oppretter issue

2023-03-14 02:50 UTC, merged